[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 2
evm_version = "cancun"
remappings = [
  "v4-core/=lib/v4-core/",
  "v4-periphery/=lib/v4-periphery/",
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/"
]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 15 }

[profile.lite]
fuzz = { runs = 1000 }
invariant = { runs = 100, depth = 10 }

[profile.default.fuzz]
runs = 10000
max_test_rejects = 65536

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[doc]
out = "docs"
